### ISSUE TITLE
no status change, if physical not available (offline) ?

### ISSUE THREAD

**Issue by camelcamro** [AtomBaf/homebridge-mqtt-tasmota#10]
Hello tested it, and it is on screen - switching the icons OFF/ON and so on, but it is not checking if that is really possible and if it is changed after clicking a button. 
so, how can you be sure, that the device is answering ?
in my example, a tasmota device is loosing the WIFI, and is not reachable, but in homebridge it is showing the ICON as OFF or click on it, then goes to "ON", but you can't see if it works or not.

Is there no status check ?
eg: if device offline, then icon with "!" or whatever ?

cu

**Comment by AtomBaf** [comment]
Hi
Indeed in the present implementation there is:

1. no LWT (last will and testament) handling...
1. no feedback when clicking a button to see if the action actually happened

From what I see the first point here could be achieved and at least will handle your concern. Let me check...

**Comment by AtomBaf** [comment]
Added in v0.10.0 => update your plugin in homebridge and let me know.

**Comment by AtomBaf** [comment]
v0.10.0 does not work sorry, on it

**Comment by AtomBaf** [comment]
In fact it works, but given [this explanation](https://github.com/homebridge/HAP-NodeJS/wiki/Presenting-Erroneous-Accessory-State-to-the-User) the update from offline to online can take a long time and is not controllable.
Sorry for that, but Apple HomeKit seems picky in this.

**Comment by camelcamro** [comment]
well, it is working for me, and i can't use the "icon" to switch ON/OFF, but the icon color  ... there is no difference.
can it not be sown in the icon as "UNKNOWN" or "OFFLINE", if LWT report "Offline" or "Unknown" and then also change the ICON color or anything to see that this is OFFLINE ?

**Comment by AtomBaf** [comment]
There is no direct API to change the color or shape of the button. Sorry for that.
