### ISSUE TITLE
Update readme url, username and password

### ISSUE THREAD

**Issue by iconnor** [AtomBaf/homebridge-mqtt-tasmota#2]
I was initially getting errors.  

```
Error event on MQTT
```

I added logging of the error (e.message) which was Connection refused: Not authorized.

After some debugging, I saw that needed to add the URL (and username/password) not just to the accessory section but also to the platform.

The onConnect's config from the constructor is called both from the accessory and at the platform level during boot up.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/22875/128616200-d3fbe9d7-17c1-4a74-9356-9f6f324024f4.png">

**Comment by AtomBaf** [comment]
Sorry for the late answer, and thx for your contribution.

**Comment by AtomBaf** [comment]
One note: today the platform feature (with auto-discovery) is not tested and should be setup with care.
This will probably require some work to fix.
Also there is probably a misundertsanding in the setup example you sent. I guess one will create either an explicit list of accessories without a platform, or only a platform without accessories.
How are you currently using it ?
