### ISSUE TITLE
Sonoff RF Bridge with Tasmota - RF Smoke alarm

### ISSUE THREAD

**Issue by jat80** [AtomBaf/homebridge-mqtt-tasmota#4]
Hi there,

I'm just wondering if this plugin will help me setup some RF Smoke alarms using my Tasmota flashed Sonoff RF Bridge.

If so is there anything special in the config that I will need to do as each smoke alarm will have it's own RF code.

Thanks for your time.

**Comment by AtomBaf** [comment]
Hi
I have a very similar setup at home: several smoke sensors with RF433 capabilities, and a Sonoff RF bridge flashed with tasmota (9.5.0) to receive the radio messages.
I then setup some rules inside tasmota like this one:
```
rule1 on System#Boot DO Backlog publish2 tele/smoke_alarm_garage/STATE off ENDON on rfreceived#Data=63F076 do publish2 tele/smoke_alarm_garage/STATE on endon
```

This way any state change will trigger an MQTT message.

On the homebridge setup, a new accossory is created like this: 
```json
        {
            "accessory": "mqtt-tasmota-smoke",
            "name": "Fumee Garage",
            "url": "mqtt://my_server",
            "topic": "smoke_alarm_garage"
        }
```

The only problem so far is that when a smoke sensor is triggered, I have to manually publish an 'off' message on the MQTT topic to reset the state (Hopefully fires in the house are not happening often!).

Hope this helps.
Cheers
