### ISSUE TITLE
Tasmota on Sonoff THR316 with THS01

### ISSUE THREAD

**Issue by Tom74HH** [AtomBaf/homebridge-mqtt-tasmota#9]
I would like to integrate a Sonoff relay with a temperature/humidity sensor. Tosmata is already on the device. Is there a way to make the device compatible with homebridge-mqtt-tasmota? I am already running an IFAN03 with the plugin and would like to use the same plugin.

**Comment by AtomBaf** [comment]
Hi @Tom74HH 
You can just simply declare 2 accessories with the same topic. The first one for the temperature/humidity sensor and the second one for the relay switch.
Example:
```json
        ....
        {
            "accessory": "mqtt-tasmota",
            "type": "sensor",
            "name": "My temperature sensor",
            "url": "mqtt://my_mqtt_broker",
            "topic": "my_tasmota_topic"
        },
        {
            "accessory": "mqtt-tasmota",
            "type": "lightbulb",
            "name": "My lightbulb sensor",
            "url": "mqtt://my_mqtt_broker",
            "topic": "my_tasmota_topic"
        }
```
